image: openjdk:21

variables:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx2g"
  # 如果你有自己的 gradle.properties 设置，防止 daemon OOM
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

stages:
  - build
  - release

before_script:
  # 保证 Gradle 是最新的
  - ./gradlew wrapper --gradle-version 8.8 --distribution-type all
  # 给gradlew加执行权限
  - chmod +x gradlew

# Step1. 正常构建
build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 hour

# Step2. 打Tag并推送（可选）
# 你可以自己在GitLab设「打Tag推送触发」
# 或者写个简单脚本：检测 package.json/build.gradle.kts版本变化 ➔ 自动tag

# Step3. 发布到GitHub Release（可选）
release:
  stage: release
  only:
    - tags
  script:
    - echo "Release triggered for $CI_COMMIT_TAG"
    # 这里只是例子，一般你可以用 curl + GitHub API 自动上传
    - echo "Can add GitHub upload logic here."
